| *** Variables *** |
| ${var_SERVICE_ORDER_ID} | 716729 |
| ${var_MEMBER_ID} | ${EMPTY} |
| ${var_ACCOUNT_ID} | ${EMPTY} |
| ${var_USERNAME} | beverly |
| ${var_PASSWORD} | password |
| ${var_BROWSER} | chrome |
| ${var_WINDOW_NAME} | main |
| ${var_LOG_LEVEL} | WARN |
| ${var_URL}     | http://192.168.1.33:2915 |
| ${var_CURRENT_ERROR_MESSAGE} | ${EMPTY} |
